language: ruby
rvm:
  - 2.3.1
services:
  - mongodb
gemfile:
  - Gemfile
before_install:
  - rvm get stable --auto-dotfiles
  - gem update bundler
script:
  - cp config/mongoid.yml config/mongoid.yml
  - bundle exec rspec spec
